// Generated by gencpp from file rosie2_test/PlanSrvResponse.msg
// DO NOT EDIT!


#ifndef ROSIE2_TEST_MESSAGE_PLANSRVRESPONSE_H
#define ROSIE2_TEST_MESSAGE_PLANSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosie2_test
{
template <class ContainerAllocator>
struct PlanSrvResponse_
{
  typedef PlanSrvResponse_<ContainerAllocator> Type;

  PlanSrvResponse_()
    : success(false)  {
    }
  PlanSrvResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::rosie2_test::PlanSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosie2_test::PlanSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PlanSrvResponse_

typedef ::rosie2_test::PlanSrvResponse_<std::allocator<void> > PlanSrvResponse;

typedef boost::shared_ptr< ::rosie2_test::PlanSrvResponse > PlanSrvResponsePtr;
typedef boost::shared_ptr< ::rosie2_test::PlanSrvResponse const> PlanSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosie2_test::PlanSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosie2_test::PlanSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosie2_test::PlanSrvResponse_<ContainerAllocator1> & lhs, const ::rosie2_test::PlanSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosie2_test::PlanSrvResponse_<ContainerAllocator1> & lhs, const ::rosie2_test::PlanSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosie2_test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosie2_test::PlanSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosie2_test::PlanSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosie2_test::PlanSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosie2_test::PlanSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosie2_test::PlanSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosie2_test::PlanSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosie2_test::PlanSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::rosie2_test::PlanSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosie2_test::PlanSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosie2_test/PlanSrvResponse";
  }

  static const char* value(const ::rosie2_test::PlanSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosie2_test::PlanSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::rosie2_test::PlanSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosie2_test::PlanSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosie2_test::PlanSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosie2_test::PlanSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSIE2_TEST_MESSAGE_PLANSRVRESPONSE_H
