// Generated by gencpp from file rosie2_test/PlanSrvRequest.msg
// DO NOT EDIT!


#ifndef ROSIE2_TEST_MESSAGE_PLANSRVREQUEST_H
#define ROSIE2_TEST_MESSAGE_PLANSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseArray.h>

namespace rosie2_test
{
template <class ContainerAllocator>
struct PlanSrvRequest_
{
  typedef PlanSrvRequest_<ContainerAllocator> Type;

  PlanSrvRequest_()
    : pose_goal()  {
    }
  PlanSrvRequest_(const ContainerAllocator& _alloc)
    : pose_goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseArray_<ContainerAllocator>  _pose_goal_type;
  _pose_goal_type pose_goal;





  typedef boost::shared_ptr< ::rosie2_test::PlanSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosie2_test::PlanSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PlanSrvRequest_

typedef ::rosie2_test::PlanSrvRequest_<std::allocator<void> > PlanSrvRequest;

typedef boost::shared_ptr< ::rosie2_test::PlanSrvRequest > PlanSrvRequestPtr;
typedef boost::shared_ptr< ::rosie2_test::PlanSrvRequest const> PlanSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosie2_test::PlanSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosie2_test::PlanSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosie2_test::PlanSrvRequest_<ContainerAllocator1> & lhs, const ::rosie2_test::PlanSrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pose_goal == rhs.pose_goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosie2_test::PlanSrvRequest_<ContainerAllocator1> & lhs, const ::rosie2_test::PlanSrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosie2_test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosie2_test::PlanSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosie2_test::PlanSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosie2_test::PlanSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosie2_test::PlanSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosie2_test::PlanSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosie2_test::PlanSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosie2_test::PlanSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff242965d2ce288fcadd0d46f5526f3d";
  }

  static const char* value(const ::rosie2_test::PlanSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff242965d2ce288fULL;
  static const uint64_t static_value2 = 0xcadd0d46f5526f3dULL;
};

template<class ContainerAllocator>
struct DataType< ::rosie2_test::PlanSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosie2_test/PlanSrvRequest";
  }

  static const char* value(const ::rosie2_test::PlanSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosie2_test::PlanSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseArray pose_goal\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseArray\n"
"# An array of poses with a header for global reference.\n"
"\n"
"Header header\n"
"\n"
"Pose[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::rosie2_test::PlanSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosie2_test::PlanSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose_goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosie2_test::PlanSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosie2_test::PlanSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "pose_goal: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseArray_<ContainerAllocator> >::stream(s, indent + "  ", v.pose_goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSIE2_TEST_MESSAGE_PLANSRVREQUEST_H
