/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Robotiq2fGripperControl
{
    public class UnityGripperRequest : Message
    {
        public const string RosMessageName = "robotiq_2f_gripper_control/UnityGripper";

        public bool open_close { get; set; }
        // open 0 close 1

        public UnityGripperRequest()
        {
            this.open_close = false;
        }

        public UnityGripperRequest(bool open_close)
        {
            this.open_close = open_close;
        }
    }
}
