/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Robotiq2fGripperControl
{
    public class UnityGripperResponse : Message
    {
        public const string RosMessageName = "robotiq_2f_gripper_control/UnityGripper";

        public string gripper_state { get; set; }

        public UnityGripperResponse()
        {
            this.gripper_state = "";
        }

        public UnityGripperResponse(string gripper_state)
        {
            this.gripper_state = gripper_state;
        }
    }
}
