// Generated by gencpp from file robotiq_2f_gripper_control/UnityGripper.msg
// DO NOT EDIT!


#ifndef ROBOTIQ_2F_GRIPPER_CONTROL_MESSAGE_UNITYGRIPPER_H
#define ROBOTIQ_2F_GRIPPER_CONTROL_MESSAGE_UNITYGRIPPER_H

#include <ros/service_traits.h>


#include <robotiq_2f_gripper_control/UnityGripperRequest.h>
#include <robotiq_2f_gripper_control/UnityGripperResponse.h>


namespace robotiq_2f_gripper_control
{

struct UnityGripper
{

typedef UnityGripperRequest Request;
typedef UnityGripperResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UnityGripper
} // namespace robotiq_2f_gripper_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotiq_2f_gripper_control::UnityGripper > {
  static const char* value()
  {
    return "b8f9390b552cf214da09ba18942db4b9";
  }

  static const char* value(const ::robotiq_2f_gripper_control::UnityGripper&) { return value(); }
};

template<>
struct DataType< ::robotiq_2f_gripper_control::UnityGripper > {
  static const char* value()
  {
    return "robotiq_2f_gripper_control/UnityGripper";
  }

  static const char* value(const ::robotiq_2f_gripper_control::UnityGripper&) { return value(); }
};


// service_traits::MD5Sum< ::robotiq_2f_gripper_control::UnityGripperRequest> should match
// service_traits::MD5Sum< ::robotiq_2f_gripper_control::UnityGripper >
template<>
struct MD5Sum< ::robotiq_2f_gripper_control::UnityGripperRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotiq_2f_gripper_control::UnityGripper >::value();
  }
  static const char* value(const ::robotiq_2f_gripper_control::UnityGripperRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotiq_2f_gripper_control::UnityGripperRequest> should match
// service_traits::DataType< ::robotiq_2f_gripper_control::UnityGripper >
template<>
struct DataType< ::robotiq_2f_gripper_control::UnityGripperRequest>
{
  static const char* value()
  {
    return DataType< ::robotiq_2f_gripper_control::UnityGripper >::value();
  }
  static const char* value(const ::robotiq_2f_gripper_control::UnityGripperRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotiq_2f_gripper_control::UnityGripperResponse> should match
// service_traits::MD5Sum< ::robotiq_2f_gripper_control::UnityGripper >
template<>
struct MD5Sum< ::robotiq_2f_gripper_control::UnityGripperResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotiq_2f_gripper_control::UnityGripper >::value();
  }
  static const char* value(const ::robotiq_2f_gripper_control::UnityGripperResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotiq_2f_gripper_control::UnityGripperResponse> should match
// service_traits::DataType< ::robotiq_2f_gripper_control::UnityGripper >
template<>
struct DataType< ::robotiq_2f_gripper_control::UnityGripperResponse>
{
  static const char* value()
  {
    return DataType< ::robotiq_2f_gripper_control::UnityGripper >::value();
  }
  static const char* value(const ::robotiq_2f_gripper_control::UnityGripperResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTIQ_2F_GRIPPER_CONTROL_MESSAGE_UNITYGRIPPER_H
