/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Rosie2Test
{
    public class PlanSrvRequest : Message
    {
        public const string RosMessageName = "rosie2_test/PlanSrv";

        public PoseArrayFixed pose_goal { get; set; }
        public bool plan { get; set; }

        public PlanSrvRequest()
        {
            this.pose_goal = new PoseArrayFixed();
            this.plan = false;
        }

        public PlanSrvRequest(PoseArrayFixed pose_goal, bool plan)
        {
            this.pose_goal = pose_goal;
            this.plan = plan;
        }
    }
}
