/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Robotiq2fGripperControl
{
    public class Robotiq2FGripper_robot_output : Message
    {
        public const string RosMessageName = "robotiq_2f_gripper_control/Robotiq2FGripper_robot_output";

        public byte rACT { get; set; }
        public byte rGTO { get; set; }
        public byte rATR { get; set; }
        public byte rPR { get; set; }
        public byte rSP { get; set; }
        public byte rFR { get; set; }

        public Robotiq2FGripper_robot_output()
        {
            this.rACT = 0;
            this.rGTO = 0;
            this.rATR = 0;
            this.rPR = 0;
            this.rSP = 0;
            this.rFR = 0;
        }

        public Robotiq2FGripper_robot_output(byte rACT, byte rGTO, byte rATR, byte rPR, byte rSP, byte rFR)
        {
            this.rACT = rACT;
            this.rGTO = rGTO;
            this.rATR = rATR;
            this.rPR = rPR;
            this.rSP = rSP;
            this.rFR = rFR;
        }
    }
}
