/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Robotiq2fGripperControl
{
    public class Robotiq2FGripper_robot_input : Message
    {
        public const string RosMessageName = "robotiq_2f_gripper_control/Robotiq2FGripper_robot_input";

        public byte gACT { get; set; }
        public byte gGTO { get; set; }
        public byte gSTA { get; set; }
        public byte gOBJ { get; set; }
        public byte gFLT { get; set; }
        public byte gPR { get; set; }
        public byte gPO { get; set; }
        public byte gCU { get; set; }

        public Robotiq2FGripper_robot_input()
        {
            this.gACT = 0;
            this.gGTO = 0;
            this.gSTA = 0;
            this.gOBJ = 0;
            this.gFLT = 0;
            this.gPR = 0;
            this.gPO = 0;
            this.gCU = 0;
        }

        public Robotiq2FGripper_robot_input(byte gACT, byte gGTO, byte gSTA, byte gOBJ, byte gFLT, byte gPR, byte gPO, byte gCU)
        {
            this.gACT = gACT;
            this.gGTO = gGTO;
            this.gSTA = gSTA;
            this.gOBJ = gOBJ;
            this.gFLT = gFLT;
            this.gPR = gPR;
            this.gPO = gPO;
            this.gCU = gCU;
        }
    }
}
